addSbtPlugin("com.jsuereth"       %  "sbt-pgp"                  % "1.1.1")
addSbtPlugin("com.github.gseitz"  %  "sbt-release"              % "1.0.8")
addSbtPlugin("org.scala-js"       %  "sbt-scalajs"              % "0.6.23")
addSbtPlugin("org.portable-scala" %  "sbt-scalajs-crossproject" % "0.5.0")
addSbtPlugin("org.xerial.sbt"     %  "sbt-sonatype"             % "2.3")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"            % "1.5.1")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin"    % "1.0.0")
// addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.1")
