addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.3")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.13")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"    % "1.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"   % "1.5.0")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "0.8.0")
// addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.1")
