addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.0")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"     % "0.6.4")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"    % "0.5.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"   % "1.3.3")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.1")